network = "goerli"
data-dir = "/home/user/nimbus-eth2/build/data"
jwt-secret = "/home/user/nimbus-eth2/build/data/jwt.hex"
node-name = "onchain"
# web3-url = ["http://127.0.0.1:8551", "http://0.0.0.0:8551"]
# metrics
metrics = true
metrics-address = "0.0.0.0"
metrics-port = 8008
# rest
rest = true
rest-address = "0.0.0.0"
# fee 
suggested-fee-recipient = "0xb1a92EEd6528B3B80e1d697DeDD9b312Eb8B116d"
